### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by landarts** [bainternet/Wamp-WordPress-installer#1]
I get this when i try to use the wamp-wordpress-installer

Fatal error: Call to undefined function curl_init() in C:\wamp\www\installer.php on line 160

**Comment by bainternet** [comment]
Im means that your curl extension is not enabled.
click and by your post i can see that you are using WAMPso simply click on the "W" icon in your task bar >> php >> php extensions>> php_curl and it should work.

closing (not an issue)
