### ISSUE TITLE
Fatal error: Call to undefined function curl_init() in C:\wamp\www\installer.php on line 251

### ISSUE THREAD

**Issue by mintyme777** [bainternet/Wamp-WordPress-installer#3]
tried turning on php extension in wamp php, php extensions, php_curl but it didnt resolve the problem has an one got any other ideas please.

additional  info :-

Call Stack
# Time    Memory  Function    Location

1   0.0005  738400  {main}( )   ..\installer.php:0
2   0.0005  748016  http_get_file( )    ..\installer.php:74

**Comment by bainternet** [comment]
This error can only mean one thing and that  is CURL  is not enabled correctly, try this http://joshuamcginnis.com/2008/09/16/how-to-enable-libcurl-in-wamp/
