### ISSUE TITLE
http://localhost/wordpress/installer.php - Edit?

### ISSUE THREAD

**Issue by lmsm76** [bainternet/Wamp-WordPress-installer#6]
I've follow your Youtube Tutorial how to install the installer.php.
In browser when I write in a new tab "http://localhost/wordpress/installer.php" the result it's a link to github - "bainternet / Wamp-WordPress-installer" even that in the browser bar I can see "http://localhost/wordpress/installer.php".
What I am doing wrong? My Installer.php that i've downloaded as 117Kb in size.
Thanks in advance!
Luis

**Comment by bainternet** [comment]
I have know idea way your file is 117kb or where you got it from bu if you download any of the versions that were committed here (in  the repo) the the size should be 18kb max as of version 0.3

**Comment by lmsm76** [comment]
I've been working on this during this afternoon and I found my mistake. I didn't download from here https://github.com/bainternet/Wamp-WordPress-installer/zipball/master 
I downloaded from https://github.com/bainternet/Wamp-WordPress-installer
Seems equal since the links are very near but the result, off course, it's very different.
Thank You for your Help and sorry for taking your time!
