### ISSUE TITLE
What Is The File c:\wamp\www\aaa.txt And How Do I Remove It?

### ISSUE THREAD

**Issue by SooBahkDo** [bainternet/Wamp-WordPress-installer#7]
The file c:\wamp\www\aaa.txt is present in the admin directory of our Wordpress Multisite Network installation.

I am only assuming it is related to wamp because of the name similarity.

Its existence has not been an issue until we implemented a new offsite backup service and the backups fail when they access this file.

I have tried changing the permissions to delete it etc., but it is resistant to all such efforts including resisting downloading a copy.  That seems to suggest the file may be is use by some other code, but I have no idea what.

Can you provide any guidance?

Thanks in advance.

Phil D

**Comment by bainternet** [comment]
Not sure where you got that file or how you setup the admin directory of a multisite to be in `c:\wamp\www\`  with wamp but it's got nothing to do with this script :)
