### ISSUE TITLE
Undefined variable: radios in install.php on line 276

### ISSUE THREAD

**Issue by ccheeseman** [bainternet/Wamp-WordPress-installer#8]
Hi,

I am new to WP and PHP but an experienced web developer on the windows side.  I installed WAMP and have cURL and all other extensions working.  When I go to the install page I get a undefined variable for your radios variable on line 276.  I have have done several searches but I was unable to locate this issue with anyone else.  I know this is an older script but do you have any suggestions to fix this error on my end?

Thank you.

**Comment by bainternet** [comment]
thanks, its fixed now.
