### ISSUE TITLE
Not creating database

### ISSUE THREAD

**Issue by AustinGil** [bainternet/Wamp-WordPress-installer#9]
Im having some issues with this auto installer. It looks great, but when I try to use it, it doesnt work. It looks like it is able to download the latest WP zip, create a directory and upload those files to the directory just fine, but it cant create a new database. I might be doing something wrong but I dont know what, its pretty straight forward. Ive tried creating a new database by filling out new user details, using current user details, and even using the 'root' user.

When I try to create a new user with the new database I get a SQL error. When I use current users I get a WP screen telling me that the user privileges are fine, but the database doesnt exist. Then when I check phpMyAdmin, the database is not there.

So Im pretty sure that the issue is with creating the database. Any ideas what the problem could be and how to fix it?

**Comment by rusak** [comment]
Having the same issue, unfortunately.

**Comment by bainternet** [comment]
What Would be the SQL error you get?

**Comment by AustinGil** [comment]
Hey, thanks for looking into this. I had all but given up on using this. Anyway, its been such a long time sine I posted the original issue. By now I dont remember what the error message was that I was receiving. I tried to recreate it, but now I am getting a different error:

Fatal error: Maximum execution time of 30 seconds exceeded in C:\wamp\www\installer.php on line 366
Call Stack

# Time    Memory  Function    Location

1   0.0011  317144  {main}( )   ..\installer.php:0
2   0.0012  344672  http_get_file( )    ..\installer.php:176

I know this is not the same issue as before because now its not even creating the directories. I dont want to put too much on your plate, but if you can help me get this tool set up, it would be awesome.

**Comment by bigyin101** [comment]
To prevent the 'unable to create database' error. Change line 415 in installer.php from:

$sql = 'CREATE DATABASE '.$db_name;
To:
$sql = "CREATE DATABASE IF NOT EXISTS `$db_name`";

Hope this helps.
